name: askinator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  appwrite: ^13.0.0
  cupertino_icons: ^1.0.6
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  get_it: ^7.6.4
  google_fonts: ^6.2.1
  injectable: ^1.5.4
  lottie: ^3.1.3
  mesh_gradient: ^1.3.8
  rive: ^0.13.14
  shared_preferences: ^2.3.2
  stacked: ^3.4.1
  stacked_hooks: ^0.2.4
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4


dependency_overrides:
  collection: ^1.19.1


flutter:

  uses-material-design: true

  assets:
    - assets/bat.riv
    - assets/candy.png
    - assets/candy-rotated.png
    - assets/background.jpg
    - assets/home-background.jpg
    - assets/loading.lottie
    - assets/medal-first.png
    - assets/medal-second.png
    - assets/medal-third.png
    - assets/pumpkin.lottie
    - google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
