

export function getTarget(seed) {
    return allTargets[seed % allTargets.length];
}

const allTargets = [
    "Saitama",
    "James Bond",
    "Albert Einstein",
    "Martin Luther King Jr.",
    "Cleopatra",
    "Napoleon Bonaparte",
    "Mahatma Gandhi",
    "Marie Curie",
    "Abraham Lincoln",
    "Winston Churchill",
    "Leonardo da Vinci",
    "Mother Teresa",
    "Sherlock Holmes",
    "Harry Potter",
    "Darth Vader",
    "Batman",
    "Spider - Man",
    "Luke Skywalker",
    "James Bond",
    "Wonder Woman",
    "Mickey Mouse",
    "Superman",
    "Pikachu",
    "Frodo Baggins", 
    "Hermione Granger",
    "Tony Stark",
    "Yoda",
    "Katniss Everdeen",
    "Optimus Prime",
    "Mario",
    "Gandalf",
    "Indiana Jones",
    "Black Panther",
    "Elsa",
    "Wolverine",
    "Goku",
    "Lara Croft",
    "Homer Simpson",
    "Bugs Bunny",
    "Captain Jack Sparrow",
    "The Joker",
    "Luffy",
];